### ISSUE TITLE
Failing Tests & Outstanding PRs

### ISSUE THREAD

**Issue by Zordrak** [tfutils/tfenv#101]
I hadn't realised neglect had lead to permanent failure. Apologies for allowing work and family to get in the way of basic maintenance.

I will be dealing with this.

@genevera I've approved the Travis permission request - presume you are working towards the test failures already?

**Comment by Zordrak** [comment]
@genevera Travis has been installed as an app for the tfutils Organisation, and if you accept the invite to the Organisation, I will enable your admin access to the Org Travis.

**Comment by genevera** [comment]
Cool thanks!  I'm out and about.  Will accept later

**Comment by Zordrak** [comment]
It's all sorted now.

Tests are fixed (dev versions can now have commit hashes)
"latest" only gives you stable releases unless you use latest:regex
0.12.0-alpha3+ now works as we hardhack support for the broken zip file names

#102
