### ISSUE TITLE
TFENV behind proxy

### ISSUE THREAD

**Issue by akamalov** [tfutils/tfenv#129]
Greetings,

I have ```tfenv``` behind proxy. All I had to do is to export my proxy configuration and then modify ```/usr/local/opt/tfenv/libexec/helpers``` to include ```-k``` for ```curlw``` function. 

I can do ```tfenv list-remote``` no problem.  

```
$ tfenv list-remote
0.12.5
0.12.4
0.12.3
0.12.2
0.12.1
0.12.0
0.12.0-rc1
0.12.0-beta2
0.12.0-beta1
0.12.0-alpha4
0.12.0-alpha3
0.12.0-alpha2
0.12.0-alpha1
0.11.14
$
```
However, when I try to install, it fails:

```
 $ tfenv install 0.12.3
[INFO] Installing Terraform v0.12.3
[INFO] Downloading release tarball from https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_darwin_mach.zip
-=#=-#   #     #
curl: (22) The requested URL returned error: 403 Forbidden
tfenv: tfenv-install: [ERROR] Tarball download failed

$
```

**Comment by pallxk** [comment]
Check your `TFENV_ARCH` environment variable, it seems it's set to `mach`, which should be `amd64` or unset.

**Comment by akamalov** [comment]
Its Mac, so arch env does match Mach.

**Comment by akamalov** [comment]
Answering my own question. The solution is for OSX, but I don't why would it be different from Linux. It assumes that you're behind corporate proxy, in authenticated environment.

Anyway, you need to modify your ```/usr/local/opt/tfenv/libexec/helpers``` file to include proxy information. For example:

**File: /usr/local/opt/tfenv/libexec/helpers**

```
#!/usr/bin/env bash
# Enabling proxy for the company proxy configuration
export user="XXXXXX"
export password="XXXXXXX"
export proxy="proxy.example.com"
export port="8080"

function error_and_die() {
  echo -e "tfenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
  exit 1
}

function warn_and_continue() {
  echo -e "tfenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
}

function info() {
  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
}

# Curl wrapper to switch TLS option for each OS
function curlw () {
#  local TLS_OPT="--tlsv1.2"
local OPTS="-k -x http://$user:$password@$proxy:$port $@"


  # Check if curl is 10.12.6 or above
  if [[ -n "$(command -v sw_vers 2>/dev/null)" && ("$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) || "$(sw_vers)" =~ 10\.1[3-9]) ]]; then
    TLS_OPT=""
  fi


#curl ${TLS_OPT} "$@"
curl ${OPTS} "$@"
}
```
Now, you should be able to use ```tfenv``` in proxy-authenticated environment.
