### ISSUE TITLE
Support auto install when no version is found

### ISSUE THREAD

**Issue by Kasama** [tfutils/tfenv#134]
I would like `tfenv` to be able to automatically install the latest `terraform` version when there is no `terraform` version installed.

Something like the following:
```
$ terraform plan
[INFO] No version of terraform was found
[INFO] installing terraform
[...]
[INFO] installation of terraform successful
[...]
<plan output>
```

I'm not sure if this is something you'd like to incorporate into the project, have it be a feature switch env var or something else. For now I've implemented a quick and dirty workaround that I'm using, but I'm keen on having this feature incoporated into the main project.

**Comment by Zordrak** [comment]
I'm not completely opposed to the idea, but I am concerned about breaking existing assumptions. It's plausible that existing users depend on a failure when the correct version has not be specified/installed and automatically determining for them that the run should continue with the latest version of terraform could have unintended consequences such as updating their state file's version compatability which requires manual intervention to revert.

**Comment by Kasama** [comment]
I'll try to find the time to implement it properly - with tests and all - and have it be an environment variable you can set to enable this feature. This way the current behavior will be preserved and this feature will be available as well.

I still need to mature this idea some more, but what about trying to determine the best version to install based on the state file? It would still be a problem for remote states, though...

**Comment by chuckwondo** [comment]
I suggest that perhaps instead of auto-installing the latest version, it auto-installs the version in the `.terraform-version` file in the current directory (perhaps also searching up the directory ancestry), if one is found. This is actually how I expect `tfenv use` to behave when no version is specified on the command line, similar to how `npm use` behaves when there is a `.nvmrc` file containing a node.js version.

**Comment by Zordrak** [comment]
Concur with @chuckwondo
