### ISSUE TITLE
Issue with installing Terraform 0.11.15

### ISSUE THREAD

**Issue by hawkesnc** [tfutils/tfenv#138]
Running into the following error:
➜  ~ tfenv list-remote
0.12.8
...
0.11.15
0.11.14
...

➜  ~ tfenv install 0.11.15
[INFO] Installing Terraform v0.11.15
[INFO] Downloading release tarball from https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_darwin_amd64.zip

curl: (22) The requested URL returned error: 403
tfenv: tfenv-install: [ERROR] Tarball download failed

In the releases, it's listed as: terraform_0.11.15-oci
So the executable should be: https://releases.hashicorp.com/terraform/0.11.15-oci/terraform_0.11.15-oci_darwin_amd64.zip

But tfenv is attempting to download: https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_darwin_amd64.zip

**Comment by veryhappythings** [comment]
This fixed it for me https://github.com/tfutils/tfenv/pull/139

**Comment by hawkesnc** [comment]
Nice! That works for me too. Thanks for that!

**Comment by epugavc** [comment]
yes, it's happening again
` tfenv install latest:^0.11           
Installing Terraform v0.11.15
Downloading release tarball from https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_darwin_arm64.zip
curl: (22) The requested URL returned error: 404                                                   

Tarball download failed
`

`tfenv install 0.11.15     
Installing Terraform v0.11.15
Downloading release tarball from https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_darwin_arm64.zip
curl: (22) The requested URL returned error: 404                                                   

Tarball download failed`

**Comment by vladgurovich** [comment]
Same -- Issue experienced with tfenv v3.0.0:
```
tfenv use 0.11.15
No installed versions of terraform matched '0.11.15:^0.11.15$'. Trying to install a matching version since TFENV_AUTO_INSTALL=true
Installing Terraform v0.11.15
Downloading release tarball from https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_darwin_arm64.zip
curl: (22) The requested URL returned error: 404                                                                      

Tarball download failed
Installing a matching version failed
```

please advice

**Comment by Saif-Uz-Zaman** [comment]
Any update on this issue? I still facing this issue.

```
tfenv install 0.11.15
                                                                                                                                                                                                 
Installing Terraform v0.11.15
Downloading release tarball from https://releases.hashicorp.com/terraform/0.11.15/terraform_0.11.15_darwin_arm64.zip
curl: (22) The requested URL returned error: 404                                                                                                                                                                                 

Tarball download failed
```

**Comment by woody-woods** [comment]
As a work around, setting the env for TFENV_ARCH to the amd version worked for me.

`TFENV_ARCH=amd64 tfenv install 0.11.15`
