### ISSUE TITLE
Suppress standard output in tfenv install command

### ISSUE THREAD

**Issue by arcones** [tfutils/tfenv#149]
It would be nice if, via a command line option, the standard output is suppressed for `tfenv install ` command as it could be cumbersome while using tfenv in systems like Jenkins:

![image](https://user-images.githubusercontent.com/17352086/68303984-32cb2780-00a5-11ea-92c1-92ef887290a8.png)

I haven't find any alternative, the progress bar is shown even with `> /dev/null` or a `> file` redirection.
Thank you very much, this project is great!

**Comment by Zordrak** [comment]
Please see v2.0.0-alpha in `master`. Does this work for you?

**Comment by arcones** [comment]
Thank you very much @Zordrak
I have just downloaded the v2.0.0-alpha version, and using the /dev/null redirection, the progress bar doesn't appear, so my pipeline logs will be much cleaner

**Comment by Zordrak** [comment]
If you only want to suppress the curl output, there are two new options.

TFENV_CURL_OUTPUT=2 is the default setting.

TFENV_CURL_OUTPUT=1 will use the default curl output instead of a progress bar.

TFENV_CURL_OUTPUT=0 will suppress the curl output by passing `q`
