### ISSUE TITLE
"BASH_SOURCE unbound variable" error in v2.0.0-alpha1

### ISSUE THREAD

**Issue by mgreen-sm** [tfutils/tfenv#153]
Receiving the following error running tfenv (with or without parameters):

```
tfenv/libexec/tfenv---version: line 47: BASH_SOURCE: unbound variable
```

tffenv release tag: v2.0.0-alpha1

**Comment by Zordrak** [comment]
Thank you, I will investigate. Will just be a missing default.

**Comment by Zordrak** [comment]
I am unable to reproduce this error.
It looks like for some reason BASH_SOURCE is not set.
How are you executing it? Is it definitely being interpreted by bash>=4, not ZSH or something else?

Regardless of all of that, if you go to tfenv/libexec/tfenv---version line 47 and replace `${BASH_SOURCE%/*}` with `${0%/*}` or `$(dirname ${0})`, does that fix it for you?

**Comment by mgreen-sm** [comment]
It happens on different systems either with ZSH or Bash as the default shell - bash (4.3.48) does get invoked through the shebang, though.

I do see that `BASH_SOURCE` is valid, until the use of the `log`. That is, if I comment out the `log` lines in `libexev/tfenv---version`, it works fine.

Haven't done any further debugging as to why, at this time.

**Comment by Zordrak** [comment]
That's bizarre. Why would it be complaining about BASH_SOURCE but only when the debug log lines are present O_o.

Appreciate anything you can do to work out what's going on, or better to help me to be able to reproduce the problem.

FWIW there is new debugging functionality that I haven't documented yet, it might be worth trying.
TFENV_DEBUG=3 tfenv ...

**Comment by mgreen-sm** [comment]
Quite odd indeed! Thankfully I came across the following: https://stackoverflow.com/questions/37952311/bash-caller-builtin-stops-working-from-exported-function-why

As mentioned in my earlier comment, this occurs when using Bash 4.3.x (default for Ubuntu 16.04 LTS). I've tested it on another system with Bash 4.4(.19) (Default for Ubuntu 18.04 LTS) and it works fine there. So it is just hitting that particular bug in the older version of Bash -- unfortunately Ubuntu 16.04 doesn't provide 4.4 in its own package repos.

That said, using `$0` gives me the same result as `$BASH_SOURCE` in that particular script, and removing the -u set flag simply ignores it without further problems...

**Comment by Zordrak** [comment]
Let me see what travis says on 16.04

**Comment by Zordrak** [comment]
https://travis-ci.com/tfutils/tfenv/jobs/260227632

Still can't reproduce it ^ :-/

**Comment by mgreen-sm** [comment]
Hmm. I could replicate it with this:

```
docker run --rm -it ubuntu:16.04 /bin/bash
(Inside container)
bash --version
(Gives GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu) )
apt update && apt install git -y
cd /opt && git clone https://github.com/tfutils/tfenv.git
./tfenv/bin/tfenv -v
(Gives /opt/tfenv/libexec/tfenv---version: line 47: BASH_SOURCE: unbound variable)
```

**Comment by Zordrak** [comment]
Interesting. travis was using 4.3.11 not 4.3.48. Perhaps the bug was introduced later in 4.3.

At least if it can be reproduced in docker I should have a starting point. Thanks!

**Comment by Zordrak** [comment]
Seems like replacing `${BASH_SOURCE%/*}` with `$(dirname ${0})` does the trick, at least in the container you specified.

Having made the change in the logging branch (along with making the debug lines clearer):

```
$ docker run --mount source="$(pwd)",target=/opt/tfenv,type=bind -it ubuntu:16.04 /bin/bash
root@bcf0a18ab3b5:/# bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
```
<snip>
```
root@bcf0a18ab3b5:/# apt update && apt install git -y
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]          
```
<snip>
```
Get:18 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8807 B]                                                                                  
Fetched 16.2 MB in 14s (1148 kB/s)                                                                                                                                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
```
<snip>
```
Fetched 19.4 MB in 19s (984 kB/s)                                                                                                                                          
```
<snip>
```
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
root@bcf0a18ab3b5:/# /opt/tfenv/bin/tfenv --version
tfenv 2.0.0-alpha1-3-g6bdf8c4
root@bcf0a18ab3b5:/# TFENV_DEBUG=2 !!
TFENV_DEBUG=2 /opt/tfenv/bin/tfenv --version
[DEBUG] Sourcing helpers from /opt/tfenv/lib/helpers.sh
/opt/tfenv/bin/tfenv: DEBUG trap set
/opt/tfenv/bin/tfenv: Helpers sourced successfully
/opt/tfenv/bin/tfenv: Prepending /opt/tfenv/libexec to PATH
/opt/tfenv/bin/tfenv: Setting TFENV_DIR to /
/opt/tfenv/bin/tfenv: tfenv version requested...
/opt/tfenv/libexec/tfenv---version: TFENV_ROOT already defined as /opt/tfenv
/opt/tfenv/libexec/tfenv---version: TFENV_HELPERS is set, not sourcing helpers again
/opt/tfenv/libexec/tfenv---version: Scraping tfenv version from CHANGELOG.md
/opt/tfenv/libexec/tfenv---version: Found version '2.0.0-alpha1' in CHANGELOG.md
/opt/tfenv/libexec/tfenv---version: Git configuration found. Overriding CHANGELOG version from git revision...
/opt/tfenv/libexec/tfenv---version: Stripping git revision string from v2.0.0-alpha1-3-g6bdf8c4
tfenv 2.0.0-alpha1-3-g6bdf8c4
root@bcf0a18ab3b5:/#
```

**Comment by Zordrak** [comment]
https://travis-ci.com/tfutils/tfenv/builds/138122705

**Comment by mgreen-sm** [comment]
Cheers - I've checked it locally, and works without any issues now
