### ISSUE TITLE
Add -q / --quiet

### ISSUE THREAD

**Issue by jstrese** [tfutils/tfenv#159]
**Feature Request**
Add a "quiet" parameter to silence the download status when installing a new version of Terraform.

Short-hand: -q
Long: --quiet

**Desired Behavior**
When: running tfenv -q install 0.12.17
Then:  The following should not print: download progress should not show (all of the pound signs),  inflating message and archive message should be hidden
Why: The download progress text clutters log files

**Comment by Zordrak** [comment]
Take a look at v2.0.0-alpha3
It has options to modify/suppress curl output

**Comment by tbugfinder** [comment]
I've also added tfenv within a CI job. The tf install output should be quiet however I couldn't find the proper switch.

**Comment by jstrese** [comment]
@tbugfinder the way to silence the curl output is by setting TFENV_CURL_OUTPUT to 0:

`TFENV_CURL_OUTPUT=0 tfenv install`
