### ISSUE TITLE
Consider making `tfenv install` switch to that version even if already installed

### ISSUE THREAD

**Issue by DrPhil** [tfutils/tfenv#164]
It's easy to switch to a version if you know it is not installed.
```
❯ sudo tfenv install 0.12.18
[INFO] Installing Terraform v0.12.18
... omitted ...
[INFO] Switching completed
```
and it is easy to switch to a version if you know it is installed:
```
❯ sudo tfenv use 0.12.18
[INFO] Switching to v0.12.18
[INFO] Switching completed
```
But if you don't remember if it is installed or not (or if you are a script), then it is more difficult. There is no "switch to  version, install if needed" command, since `terraform install` will abort if the version is already installed.
```
❯ sudo tfenv install 0.12.19
Terraform v0.12.19 is already installed

❯ terraform version
Terraform v0.12.18
```

This can of course be circumvented by always using `tfenv list` first, but is more cumbersome than needed. I would prefer `tfenv install` to always switch to the given version, no matter if it is currently installed or not. Is a PR welcome?

Thanks for a great project. <3 Much love!

#nit-picking #enhancement

**Comment by Zordrak** [comment]
Per #167, tfenv is changing to never invoke use on install
