### ISSUE TITLE
Add a "detect" subcommand to check if tfenv is in use

### ISSUE THREAD

**Issue by matschaffer** [tfutils/tfenv#166]
I'd like to avoid specifying my terraform version in multiple places. tfenv is helpful for this since i can drop a `.terraform-version` at any point in the project where I need to pin, but it's difficult to ensure tfenv is being used.

For the moment I've done this in my Makefile:

```
# Raw terraform will be binary, tfenv is a script so we detect tfenv via file type
terraform_is_script = $(shell file $$(which terraform) | grep -q script; echo $$?)

.PHONY: ensure-tfenv
ensure-tfenv:
ifeq ($(terraform_is_script),1)
	$(error Please install & configure https://github.com/tfutils/tfenv to use this tree)
endif
```

But it seems a little fragile to to just assume that a script means tfenv is in use.

**Comment by Zordrak** [comment]
I'm not quite sure how we would go about that without interfering with the execution process. tfenv is a call to tfenv, but terraform is a direct exec to the correct terraform binary without trapping or modifying any parameters. An additional command to tfenv wouldn't technically prove that the tfenv terraform script has priority in your PATH, and adding a custom parameter to a terraform command would interfere with the intended transparency to the raw binary.

Perhaps something like this would better suit your needs? It's not perfect, but it would give you what you need without ambiguity:

`TFENV_DEBUG=1 terraform 2>&1 | grep TFENV_DIR && echo 'tfenv detected'`

**Comment by matschaffer** [comment]
Ah, that's much nicer. 

`terraform tfenv-detect` could be interesting, but I agree it might muck up the CLI processing works. 

I'm happy to close this with `TFENV_DEBUG ... | grep` as the solution for detecting tfenv presence.
