### ISSUE TITLE
COMMUNITY VOTE - Install always invokes use OR Install never invokes use

### ISSUE THREAD

**Issue by Zordrak** [tfutils/tfenv#167]
This has been bugging me for a while and there are exitsing open issues that relate to it (e.g. https://github.com/tfutils/tfenv/issues/164)

A decision needs to be made that will break backward compatability one way or the other.

Please vote with reactions to this content.

👍 = You want install to always invoke use. If the version is not installed, it will install it and then switch the default version to it. If the version is installed, it will just switch the default version to it.

👎 = You want install to never invoke use. Whether the version is installed or not, the default version will not be changed without invoking use explicitly.

Note: this will not affect versions selected by a min_required or .terraform-version file. As per the change in https://github.com/tfutils/tfenv/tree/v2.0.0-beta1 the `use` command changes only the *default* version which is defined by the symlink at ${TFENV_ROOT}/version.

**Comment by conzy** [comment]
Similar issue here https://github.com/tfutils/tfenv/issues/131

Calling `tfenv use` and writing to the .terraform-version massively violates the principle of least surprise.

**Comment by digitalfiz** [comment]
100% this should not touch the `.terraform-version` file at all regardless of this behavior

**Comment by Zordrak** [comment]
Just to reiterate, that issue has been resolved in 2.0.0-beta1, the question that remains is solely whether install invokes use, which only affects the default version which is used when  .terraform-version file is not present.

**Comment by Zordrak** [comment]
Decision is clear. Install will change to not invoke use.
