### ISSUE TITLE
Tried update cask formula to 2.0.0

### ISSUE THREAD

**Issue by rafilkmp3** [tfutils/tfenv#180]
I tried to to update a formula to 2.0.0 but seens something changed and wont pass on tests...

https://github.com/Homebrew/homebrew-core/pull/53964/checks?check_run_id=629425938

**Comment by chenrui333** [comment]
@rafilkmp3 minor correction, is core formula instead of cask formula.

To echo his comment, there is more comprehensive discussion in this PR (https://github.com/Homebrew/homebrew-core/pull/53959), it looks like the latest tfenv depends on latest bash rather than the system default bash.
