### ISSUE TITLE
Error: "unbound variable" when running list or list-remote commands

### ISSUE THREAD

**Issue by llirikkk** [tfutils/tfenv#183]
When I run either "list" of "list-remote" commands on Mac OS, I get the following error:
`.tfenv/bin/tfenv: line 107: @: unbound variable`

"install" and "use" commands work fine.

**Comment by ctrlaltdev** [comment]
Having the same issue as @llirikkk - I'm not seeing the issue on v1.0.2 though

**Comment by Zordrak** [comment]
Can you test the master branch? This issue should now be resolved and if so will be released in the near future.

**Comment by ctrlaltdev** [comment]
@Zordrak Sorry for the 2 months ghosting.
Tested on master (`tfenv --version` -> `tfenv 2.0.0-37-g0494129`) and it seems to work!
Didn't get the error with either command
