### ISSUE TITLE
Dockerized tfenv

### ISSUE THREAD

**Issue by danielcn** [tfutils/tfenv#185]
Hi there,
Is there any official docker image for this project? Thanks!

**Comment by Zordrak** [comment]
There is not. While I maintain my own docker images for specific projects that might need a quickstart terraform configuration, the installation requirements for tfenv are so simple that it doesn't seem worth there being an official image.

FWIW if you want to include tfenv in a docker image of your own, you need little more than:

```
RUN git clone https://github.com/tfutils/tfenv.git /opt/tfenv \
    && ln -s /opt/tfenv/bin/* /usr/local/bin
```
