### ISSUE TITLE
[ERROR] 'terraform --version' failed

### ISSUE THREAD

**Issue by Roxyrob** [tfutils/tfenv#194]
Found similar issue as #116 in tfenv use command:

tfenv use 0.13.0-beta2

returns

Switching default version to v0.13.0-beta2
Error parsing command-line flags: flag provided but not defined: -version

'terraform --version' failed. Something is seriously wrong

Nothing bad as the new terraform version is pointed anyway by tfenv, but probably you can avoid this using "terraform version" instead of removed "--version" option to prepare to new terraform 0.13 release

**Comment by Zordrak** [comment]
Resolved by #191
