### ISSUE TITLE
Install AND use at same time?

### ISSUE THREAD

**Issue by red8888** [tfutils/tfenv#227]
I have some automation scenarios id like to run this in

I would be nice if I could run `tfenv install 'latest:^0.13'` and have it install AND activate that version

Otherwise (if im scripting this) I have to install, then try to capture the output and parse out the version it downloaded before passing it to tfenv use.

The fact that it will pull down the latest version based on regex is nice but if it could 'use' that version it downloads automatically too that would be even better.

for example id want to be able to do something like this:
`tfenv use 'latest:^0.12'`

And have tfenv download, install and use the latest 0.12.* version. Right now that command switches to my _locally_ installed latest version it seems

**Comment by jstrese** [comment]
You can accomplish this by writing the version to a .terraform-version file, then calling 'tfenv install'. It will install the version in the file and then use it automatically. To switch versions you can just echo a new version to the file and it will automatically switch to it, if installed. This is what we use to automate our CICD process.

See: https://github.com/tfutils/tfenv#terraform-version-file

```
$ cat .terraform-version
0.6.16

$ terraform --version
Terraform v0.6.16

Your version of Terraform is out of date! The latest version
is 0.7.3. You can update by downloading from www.terraform.io

$ echo 0.7.3 > .terraform-version

$ terraform --version
Terraform v0.7.3

$ echo latest:^0.8 > .terraform-version

$ terraform --version
Terraform v0.8.8
```

**Comment by Zordrak** [comment]
This was an intentional choice made as a result of the following Community Vote: https://github.com/tfutils/tfenv/issues/167
