### ISSUE TITLE
Support GnuGPG also

### ISSUE THREAD

**Issue by jacobisaliveandwell** [tfutils/tfenv#228]
I just stumbled on how this project only verifies signatures if keybase is installed.

GnuGPG installs are nearly ubiquitous.

**Comment by anthraxx** [comment]
I would consider this project as dead:

https://github.com/tfutils/tfenv/pull/212
https://github.com/tfutils/tfenv/pull/213

**Comment by jacobisaliveandwell** [comment]
@anthraxx maybe someone should fork?

**Comment by anthraxx** [comment]
@jacobisaliveandwell i kind of already did but i found this quite badly designed and started some rust stuff. once its available i will drop it here

**Comment by iamhsa** [comment]
> I just stumbled on how this project only verifies signatures if keybase is installed.
> 
> GnuGPG installs are nearly ubiquitous.


Do you use the `trust-tfenv` directive as describe in the README ?
With this, signature is verified by GnuPG.
```
❯ cat .tfenv/use-gpgv
trust-tfenv: yes


❯ tfenv install latest
Installing Terraform v0.14.5
Downloading release tarball from https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip
########################################################################################################################################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_SHA256SUMS
Downloading SHA hash signature file from https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_SHA256SUMS.sig
gpgv: Signature made Wed 20 Jan 2021 07:22:30 PM CET
gpgv:                using RSA key 91A6E7F85D05C65630BEF18951852D87348FFC4C
gpgv: Good signature from "HashiCorp Security <security@hashicorp.com>"
Archive:  tfenv_download.kZCRn9/terraform_0.14.5_linux_amd64.zip
  inflating: /home/hugosalesses/workspace/private/tools/tfenv/versions/0.14.5/terraform  
Installation of terraform v0.14.5 successful. To make this your default version, run 'tfenv use 0.14.5'
```

**Comment by jacobisaliveandwell** [comment]
@iamhsa I did not. But I think @anthraxx brings up a good point.

**Comment by Zordrak** [comment]
The project is not dead, I have just struggled to have time in the past year due to constant demand from full-time work on projects supporting COVID response.
