### ISSUE TITLE
Create official docker image

### ISSUE THREAD

**Issue by m00lecule** [tfutils/tfenv#241]
Hello Guys! I was wondering if You got in plans to set up an official docker image?

**Comment by Zordrak** [comment]
Not an unreasonable ask.. but what would be the base?

The Dockerfile would be little more than:

FROM <base>
RUN git clone https://github.com/tfutils/tfenv.git

**Comment by m00lecule** [comment]
Honestly I would suggest to use as minimal image as possible - it could be alpine, busybox or python image based on alpine. But it might turn out insufficient - other tools from `*env` family are using ubuntu:18.04 as base image, for example [pyenv](https://github.com/pyenv/pyenv/blob/master/Dockerfile#L1)
