### ISSUE TITLE
Unable to invoke terraform when line feed is CRLF

### ISSUE THREAD

**Issue by chicken231** [tfutils/tfenv#243]
This is mostly for posterity as I've identified the cause of the problem and it's an easy fix.

`tfenv 2.2.0`

Issue:
If the `.terraform-version` file is set to `CRLF` (not `LF`), and you have an empty newline in it like so:
```
0.14.6

```

If you try to run a terraform command or `tfenv use 0.14.6`, you'll get:
```
Switching default version to v0.14.6
Default version file overridden by /BLA/BLA/.terraform-version, changing the default version has no effect
No versions matching '' found in remote
/terraform: No such file or directorynv/2.2.0/libexec/tfenv-exec: line 105: /home/linuxbrew/.linuxbrew/Cellar/tfenv/2.2.0/versions/0.14.6
'terraform version' failed. Something is seriously wrong
```

The fix:
Remove the blank newline, or switch the file's line feed to `LF`

**Comment by fractos** [comment]
This really feels like tfenv should be more robust around this. I keep hitting the issue.
