### ISSUE TITLE
TFENV_AUTO_INSTALL doesn't work if *no* version is installed

### ISSUE THREAD

**Issue by OJFord** [tfutils/tfenv#245]
I would expect that I wouldn't have to install some (arbitrary) version before `TFENV_AUTO_INSTALL` takes effect and automatically installs the correct one.

Actual:

```
# terraform
No versions of terraform installed. Please install one with: tfenv install
# echo '0.13.6' > .terraform-version
# terraform
No versions of terraform installed. Please install one with: tfenv install
# TFENV_AUTO_INSTALL=true terraform
No versions of terraform installed. Please install one with: tfenv install
# tfenv install 0.12.5
Installing Terraform v0.12.5
[...]
Installation of terraform v0.12.5 successful. To make this your default version, run 'tfenv use 0.12.5'
# terraform
version '0.13.6' is not installed (set by //.terraform-version). Installing now as TFENV_AUTO_INSTALL==true
Installing Terraform v0.13.6
[...]
Installation of terraform v0.13.6 successful. To make this your default version, run 'tfenv use 0.13.6'
Usage: terraform [-version] [-help] <command> [args]
[...]
```

**Comment by jrsherry** [comment]
It looks like this check is happening here: https://github.com/tfutils/tfenv/blob/master/libexec/tfenv-version-name#L63

Perhaps a legacy piece of code that should have been pulled out or modified with the TFENV_AUTO_INSTALL implementation?

I've found that an effective work around is to create the versions directory (i.e. `mkdir ~/.tfenv/versions`).

Perhaps some options to resolve:
1. check in the versions directory
2. remove that particular check, or have it look at the auto-install flag as well

On a somewhat unrelated note; would it make sense to set 'version' (effectively run `tfenv use` command), in the case that auto-install installs the first/only terraform version?

**Comment by next-jesusmanuelnavarro** [comment]
Also found this behaviour.

As per reading the doc, my expectation was that, once tfenv is properly configured, and because of the 'TFENV_AUTO_INSTALL' default to true, the mere presence of a '.terraform-version' file (or 'TFENV_TERRAFORM_VERSION' environment variable) would download and *"activate"* the requested Terraform version, if not already so, whenever either a `tfenv` or `terraform` command are invoked.

I found that's not the case (it does, however *"auto-activate"* the requested version once installed):
```console
$ echo $TFENV_AUTO_INSTALL

$ cat .terraform-version 
0.12.26
$ tfenv list
No versions available. Please install one with: tfenv install
$ terraform --version
No versions of terraform installed. Please install one with: tfenv install
$ tfenv use
No versions of terraform installed. Please install one with: tfenv install
$ tfenv install
Installing Terraform v0.12.26
Downloading release tarball from https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
################################################################################################################################################################# 100,0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_SHA256SUMS
No keybase install found, skipping OpenPGP signature verification
Archive:  tfenv_download.l3Y4zL/terraform_0.12.26_linux_amd64.zip
  inflating: /home/e047072/REPOS/magic-enviro/example-project/.tfenv/versions/0.12.26/terraform  
Installation of terraform v0.12.26 successful. To make this your default version, run 'tfenv use 0.12.26'
$ terraform --version
Terraform v0.12.26

Your version of Terraform is out of date! The latest version
is 0.14.8. You can update by downloading from https://www.terraform.io/downloads.html
$
```

**Comment by reegnz** [comment]
I just discovered this issue, we're experiencing the same thing.

I'm thinking that instead of failing in case the `versions` folder is missing in libexec/tfenv-version-name, it should simply continue. I shall create a PR for this.

**Comment by miqm** [comment]
I think it still does not work. I have tfenv v2.2.2 and if there are no versions installed, running terraform init does not install but just fails with message `No versions of terraform installed. Please install one with: tfenv install`:
```
# tfenv list
No versions available. Please install one with: tfenv install
# echo $TFENV_AUTO_INSTALL
true
# cat .terraform-version
1.1.3
# terraform init
No versions of terraform installed. Please install one with: tfenv install
```
even more odd is when I've `latest:^1.1.`:
```
# tfenv install 0.9.0
Installing Terraform v0.9.0
Downloading release tarball from https://releases.hashicorp.com/terraform/0.9.0/terraform_0.9.0_darwin_amd64.zip
######################################################################################################################################################################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.9.0/terraform_0.9.0_SHA256SUMS
No keybase install found, skipping OpenPGP signature verification
Archive:  tfenv_download.LHFsiP/terraform_0.9.0_darwin_amd64.zip
  inflating: /usr/local/Cellar/tfenv/2.2.2/versions/0.9.0/terraform
Installation of terraform v0.9.0 successful. To make this your default version, run 'tfenv use 0.9.0'
# echo "latest:^1.1." > .terraform-version
# terraform init
No installed versions of terraform matched 'latest:^1.1.'
```

**Comment by miqm** [comment]
Damn, I just realised that v2.2.2 is from June, and fix was merged in August. Will there be some release in near future?

**Comment by OJFord** [comment]
@miqm That's been asked in #295, but nothing (commits neither) since then, maintainers seem to have other priorities at the moment.
