### ISSUE TITLE
curl: (60) SSL certificate problem: unable to get issuer certificate

### ISSUE THREAD

**Issue by tcal-repo** [tfutils/tfenv#249]
tfenv v2.2.0 installed using WSL on Windows.

Have not had to install newer version of terraform for while, but running into issue below trying to tfenv install or even just tfenv list-remote.

```
$ tfenv list-remote
curl: (60) SSL certificate problem: unable to get issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Failed to download remote versions from https://releases.hashicorp.com/terraform/
```

No issues previously, has anything changed with v2.2.0 that might cause this?

**Comment by Suraj-Project** [comment]
@tcal-repo I am facing same issue. did you manage to get around ?

**Comment by jar145** [comment]
@tcal-repo I am facing the same issue as well. Any updates on this?

**Comment by jar145** [comment]
@tcal-repo, @Suraj-Project I just figured it out. It was some security software on my company computer called Netskope. I was able to narrow down the issue and figured out that any curl command produced a similar error. You can try on your end to verify.
Example: run `curl https://api.ipify.org?format=json'` or `curl https://google.com'`

I disabled Netskope for now and it works. In the meantime, I'm working with our security department to figure out the issues. However, as far as I can tell it's not a tfenv issue.

**Comment by Suraj-Project** [comment]
good to hear that @jar145 .
To make it work, I had to run below commands.

echo insecure >> ~/.curlrc
echo 'trust-tfenv: yes' > ~/.tfenv/use-gpgv
