### ISSUE TITLE
Fix release v2.2.1 download

### ISSUE THREAD

**Issue by sushant-pradhan** [tfutils/tfenv#262]
Click of https://github.com/tfutils/tfenv/releases/latest leads to https://github.com/tfutils/tfenv/releases/tag/v2.2.1 or the following also returns v2.2.1:
```bash
curl -fs "https://api.github.com/repos/tfutils/tfenv/releases/latest" | jq -r .tag_name
```
However, the file is not present to be downloaded: https://github.com/tfutils/tfenv/archive/v2.2.1.zip

It works fine for previous versions though (eg. v2.2.0).

**Comment by anthraxx** [comment]
the mentioned links work here and the zip can be downloaded
