### ISSUE TITLE
Creating an environment variable bringing the current tfenv version name ?

### ISSUE THREAD

**Issue by ginolegigot** [tfutils/tfenv#298]
Hello!
When we activate a pyenv, an environment variable named VIRTUAL_ENV is created.
This would be very convenient to have the same feature with tfenv, especially to print the current used tf version in a zsh prompt.
Do you think it would be possible to implement such a feature ?

**Comment by ginolegigot** [comment]
Thank you for your answer, I ended up writing a function i pasted in my .zshrc.
```bash
function tfu {
  tfenv use $1 && export TFENVVERSION=$(tfenv version-name)
}
```
So that after each tfuse i'm sure to have a proper environment TFENVVERSION environment variable i can quickly obtain which enhances a lot my powerlevel10k prompt customization.
Cheers!

**Comment by OJFord** [comment]
If you only change version by `tfenv use` I suppose that's fine, just beware of the caveat I mentioned above if you might ever use a `.terraform-version` file, or if you `tfenv use min-required` for that matter.

**Comment by ginolegigot** [comment]
All right, thanks!
