### ISSUE TITLE
tfenv use failed with Version directory for XXX is present, but the terraform binary is not executable! Manual intervention required.

### ISSUE THREAD

**Issue by hayorov** [tfutils/tfenv#308]
tfenv use latest:^0.14
Version directory for 0.14.11 is present, but the terraform binary is not executable! Manual intervention is required.

File is executable 
bash-5.1# file /opt/tfenv/versions/0.14.11/terraform
+ file /opt/tfenv/versions/0.14.11/terraform
/opt/tfenv/versions/0.14.11/terraform: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=g-wQ15BcyAzPGJhwZiNj/L5ibejvHbfTgM727PEMZ/DcPYBwUOv_-yLBdDudyM/juUJ9-z_DoWR9JnnNRo1, not stripped

+ bash --version
GNU bash, version 5.1.4(1)-release (x86_64-alpine-linux-musl)

bash-5.1# tfenv use latest:^0.14
+ tfenv use 'latest:^0.14'
+ '[' -x /opt/tfenv/versions/0.14.11/terraform ']'
+ log error 'Version directory for 0.14.11 is present, but the terraform binary is not executable! Manual intervention required.'

bash-5.1# cat /etc/issue 
+ cat /etc/issue
Welcome to Alpine Linux 3.14
Kernel \r on an \m (\l)

+ uname -a
Linux 19bb62821a6e 3.10.0-1127.13.1.el7.x86_64 #1 SMP Fri Jun 12 14:34:17 EDT 2020 x86_64 Linux

**Comment by hayorov** [comment]
It's actually weird 

```
bash-5.1# test -x /usr/bin/ls
+ test -x /usr/bin/ls
bash-5.1# echo $?
+ echo 1
1
```

**Comment by allenhumphreys** [comment]
@hayorov I think you've run into this issue introduced in Alpine Linux 3.14. https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

**Comment by hayorov** [comment]
@allenhumphreys U are right, that was just the first thing ... that I discovered. 

Close issues.

**Comment by allenhumphreys** [comment]
@joshmyers if you look at the alpine 3.14 release notes there are instructions for updating your container runtime settings to fix the issue. 


Downgrading to alpine 3.13 temporarily was my fix while we push host OS and docker updates.

**Comment by ndlanier** [comment]
I'm seeing this issue on a debian based image. I can't exactly change it while it's up because this is being done on a jenkins task agent and it is hit or miss if it happens.
```
+ tfenv install 1.1.2
Installing Terraform v1.1.2
Downloading release tarball from https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
#=#=#                                                                         
#####                                                                      7.9%
########################################                                  55.7%
######################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_SHA256SUMS
Not instructed to use Local PGP (/home/jenkins/.tfenv/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification
Archive:  /tmp/tfenv_download.0YriGo/terraform_1.1.2_linux_amd64.zip
  inflating: /home/jenkins/.tfenv/versions/1.1.2/terraform  
Installation of terraform v1.1.2 successful. To make this your default version, run 'tfenv use 1.1.2'
+ tfenv use 1.1.2
Version directory for 1.1.2 is present, but the terraform binary is not executable! Manual intervention required.
script returned exit code 1
```
