### ISSUE TITLE
Update documentation for brew

### ISSUE THREAD

**Issue by johnwesley** [tfutils/tfenv#318]
When installed with **brew** (OS X), the root directory won't be in the user's home directory. It will most likely live in `/usr/local/Cellar/tfenv/2.2.2`, for example. The issue here, is where to touch `use-gpgv` and `use-gnupg`. A user might follow the documentation and write these file to a brand new `~/.tfenv/` after a `brew install` and this alone won't work.

I would suggest adding a small note about this in the docs.

**Comment by gchappel** [comment]
Hey, just a thought - could this be improved so that the preference COULD be set in the homedir? I tend to like preferences to be stored in my homedir, and when Homebrew upgrades, it'll remove the `3.0.0` directory and create a new `3.0.1` without the `use-gpgv` or `use-gnupg` files

**Comment by gchappel** [comment]
Never mind, checking the code I see that I can simply override the `TFENV_CONFIG_DIR` variable in my shell profile and take preferences from my homedir that way
