### ISSUE TITLE
Failed to create the File

### ISSUE THREAD

**Issue by luisbattle** [tfutils/tfenv#320]
Step to reproduce de Issue
Try to install terraform version:
  I used this command:
  tfenv install 1.0.0
  
  warning: Failed to create the file                                             
  Warning: /tmp/tfenv_download.VbIIlY/terraform_1.0.0_linux_amd64.zip: No such 
  Warning: file or directory
  curl: (23) Failure writing output to destination

Tarball download failed

SO VERSION
------------------
cat /etc/os-release 
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

I installed the tf env using this steps:
$ git clone https://github.com/tfutils/tfenv.git ~/.tfenv
$echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
$ ln -s ~/.tfenv/bin/* /usr/local/bin
$ mkdir -p ~/.local/bin/
$ . ~/.profile
$ ln -s ~/.tfenv/bin/* ~/.local/bin
$ which tfenv

Whats is wrong? 
Thanks in advanced

**Comment by luisbattle** [comment]
hi, any update about this issue ?

**Comment by worzel666** [comment]
Are you able to reliably recreate this? If you run `df -h /tmp` what is the output please?

**Comment by luisbattle** [comment]
hi @worzel666 
I reinstall the WSL and then it worked fine... So I think we can close the ticket.
