### ISSUE TITLE
v2.2.3: Cannot install anything below v1.0.2 terraform, cURL 403 error

### ISSUE THREAD

**Issue by snypelife** [tfutils/tfenv#323]
## Specs
OS: macOS 12.1
CPU: M1 Pro ARM64

## Expected
To install any arm64 version of terraform, to work with the M1 Mac.

## Actual
Attempting to install anything below v1.0.2 of terraform results in a 403 error. Possible duplicate https://github.com/tfutils/tfenv/issues/319 ?

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1965406/154149178-4a4fc3ba-2274-4987-90a9-83d6ade6b919.png">

## Workaround 
By using `TFENV_ARCH=amd64` I can get it to install, but that doesn't seem right given the arch?

## Notes
Version 2.2.2 of tfenv did not have this issue. Or at least I was unable to reproduce it with 2.2.2.

**Comment by snypelife** [comment]
Tried additional v1 versions, encountered some errors.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/1965406/154150357-593bc680-b5db-4c8e-b460-6c5dd5e22c63.png">

**Comment by worzel666** [comment]
If you browse the directories in your browser you should be able to see that Terraform began to be built for arm64 as of 1.0.2. I believe the previous version of tfenv would previously have erroneously set the TFENV_ARCH to amd64 if you hadn’t set it yourself. The binary would have been present at the constructed URL and no error would have been returned. The behaviour you are seeing is actually correct!

**Comment by jack-parsons-bjss** [comment]
That's exactly it :) As this is correct behaviour, I'm going to close this issue.

**Comment by worzel666** [comment]
That's exactly it :) As this is correct behaviour, I'm going to close this issue.
