### ISSUE TITLE
Add flag to use proxy when calling `tfenv install`

### ISSUE THREAD

**Issue by torbendury** [tfutils/tfenv#326]
Hello everyone,

I have no clue how to configure `tfenv` to respect e.g. a company proxy. Do I need to set global variables? Is it a big deal to add a `--proxy` flag to the tool? Unfortunately, I'm not able to use `tfenv` otherwise without access to the public internet. Which global environment variables does it respect?

**Comment by worzel666** [comment]
General practise for proxies is to export all of `http_proxy`, `https_proxy`, `HTTP_PROXY` and `HTTPS_PROXY` which will be picked up by the subsequent cURL commands run by the script.

**Comment by torbendury** [comment]
Hey, thanks for the quick response. `curl` was the keyword to know, so the environment variables should be pulled from there.

Am I able to force `tfenv` to use IPv4? My proxy has _some_ issues with IPv6.

**Comment by torbendury** [comment]
I think I can close this for now.

Again, for anyone looking into this who has issues with their company proxy using IPv4, you can hack your way into it when checking out the repository with something like this:

```bash
  sed -i 's/--tlsv1.2/--tlsv1.2 --ipv4/g' "$WORKSPACE/.tfenv/lib/helpers.sh"
```

@worzel666 thanks for the hints regarding `tfenv` utilizing curl under the hood.
