### ISSUE TITLE
Can't install old terraform versions with arm architechture

### ISSUE THREAD

**Issue by CollinLeishman** [tfutils/tfenv#327]
On an M1 mac, I'm unable to install older terraform versions. It is attempting to grab the arm64 zip, so I'm not sure what the issue is.

```
tfenv install 0.14.9
Installing Terraform v0.14.9
Downloading release tarball from https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_darwin_arm64.zip
curl: (22) The requested URL returned error: 403

Tarball download failed
```

```
[me@MacBook-Pro] arch
arm64
```

**Comment by worzel666** [comment]
This issue is caused by Terraform not supporting arm64 until version 1.0.2; if you want to use that version of Terraform you’ll need to set your architecture to arm rather than arm64 using the TFENV_ARCH environment variable.

**Comment by CollinLeishman** [comment]
Good to know. Thanks!
