### ISSUE TITLE
tfenv throwing error Failed to download remote version 

### ISSUE THREAD

**Issue by amansingh14** [tfutils/tfenv#328]
Hi, I installed tfenv version 2.2.3 yesterday on ubuntu machine and getting following error from the time of installation.

`amazesingh@ROG-Strix:~/.tfenv/bin$ tfenv --version
tfenv 2.2.3
`
ERROR:

`amazesingh@ROG-Strix:~/.tfenv/bin$ tfenv list-remote
environment: line 4: curl: command not found
Failed to download remote versions from https://releases.hashicorp.com/terraform/
`
Kindly, help on above issue.

Thanks,
Aman SIngh

**Comment by anthonyagresta** [comment]
try `sudo apt update && sudo apt install curl`

**Comment by amansingh14** [comment]
I forgot its new installation. Thanks it fixed the problem.
