### ISSUE TITLE
Version 0.12.19 access denied - 403

### ISSUE THREAD

**Issue by dhananjay-thakur** [tfutils/tfenv#329]
$ tfenv install 0.12.19
[INFO] Installing Terraform v0.12.19
[INFO] Downloading release tarball from https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_darwin_arm64.zip
#=#=-#  #                                                                      
curl: (22) The requested URL returned error: 403 
Tarball download failed

Also, I am getting 403 - Forbidden error while accessing this link:
https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_darwin_arm64.zip

**Comment by harsha-chamarthi** [comment]
Hello @dhananjay-thakur, this is failing because darwin_arm64 does not exist. There is only (https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_darwin_amd64.zip)
