### ISSUE TITLE
terraform output is getting extra content 

### ISSUE THREAD

**Issue by uday-projectn** [tfutils/tfenv#344]
`terraform output -raw ssh_key`

Should give only the ssh key, but getting below output.

![image](https://user-images.githubusercontent.com/103102560/179078083-2b385eac-60a4-4257-91f4-c4ed22cbbf8e.png)

Not coming if we use direct terraform but coming with the version installed using tfenv.

`Executing: /home/vagrant/.tfenv/versions/1.2.5/terraform output -raw ssh_command`

**Comment by jacobdonenfeld** [comment]
This would be fixed in #343

**Comment by Zordrak** [comment]
Fixed in #345
