### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by agusterodin** [tfutils/tfenv#358]
Would you be interested in setting up GitHub Sponsors? Our organization loves this tool and would like to donate.

**Comment by Zordrak** [comment]
Hi @agusterodin . Having given this due consideration, I'm not sure that there's appropriate justification to set up GitHub Sponsors. The project has no ongoing costs other than my time; and I'm not in a position to provide any level of guaranteed time - I do what I can when I can. Therefore as much as donations would be gratefully received, I've nothing to give in return. Also, as soon as any sizeable contribution were made, I would then lose additional time to addressing the taxable income with the UK Revenue & Customs service.

However, I thank you for your interest in supporting the project financially.
