### ISSUE TITLE
tfenv downloaded a Terraform 013.3 version that is being flagged as malware

### ISSUE THREAD

**Issue by mdiianni** [tfutils/tfenv#393]
Hello there, today MacOs on my machine reported terraform downloaded via tfenv as malware! Please review.

![image](https://user-images.githubusercontent.com/2330249/234324469-79c4a4ea-323d-4b9c-9422-d28d712b1f6a.png)

**Comment by mjuarez** [comment]
Actually, you may want to read this over in case this was a previously downloaded version: https://discuss.hashicorp.com/t/hcsec-2023-01-hashicorp-response-to-circleci-security-alert/48842/2

**Comment by mdiianni** [comment]
Looks like the issue has been contained and should not impact Terraform users.

**Comment by rpdelaney** [comment]
We are affected by this. Some guidance would be appreciated! Is it enough to uninstall and reinstall the terraform versions used in `tfenv`?

**Comment by boweeb** [comment]
Since it isn't clear what the thumbs-up reaction above actually means, I'll note here explicitly that reinstalling via `tfenv uninstall <version>` and `tfenv install <version>` will in fact clear the message. 🎉

**Comment by rpdelaney** [comment]
Yep! That fixed it. This script should reinstall all the versions (it's the only way to be sure):

```sh
#!/usr/bin/env bash
#

for version in $(tfenv list | tr -s ' ' | cut -d ' ' -f 2); do 
  (set -x ; tfenv uninstall "$version" && tfenv install "$version")
done
```

**Comment by nodesocket** [comment]
Would be nice to add a `tfenv install --force <version>` flag.
