### ISSUE TITLE
How does the terraform version get set, what environment vars are needed?

### ISSUE THREAD

**Issue by btilford** [tfutils/tfenv#74]
Running into an [issue](https://youtrack.jetbrains.com/issue/WEB-29148) in IntelliJ/Webstorm that allows running `terraform fmt` etc on commit. 

It exits with `~/.tfenv/bin/terraform: line 6: exec: tfenv: not found`.

Is there a way to make this work editing a bash profile or rc?

**Comment by kamatama41** [comment]
@btilford 
Sorry for late reply. Is it still happening?
Since #72 might resolve your problem, please update to the latest version if your version doesn't have the commit.

**Comment by btilford** [comment]
@kamatama41 I pulled down master and retried still get the error.
```
tfenv -v
tfenv 0.6.0
```

![image](https://user-images.githubusercontent.com/248725/32293443-c3541c98-bf08-11e7-9c82-8094191f3dab.png)

**Comment by btilford** [comment]
Still no luck.

**Comment by kamatama41** [comment]
@btilford 
Thank you for the information.
I'll take a look at it when having a time.

**Comment by espoelstra** [comment]
@btilford I believe this issue stems from the fact that the JetBrains products tend to reset the PATH when launched. If you open the IDE using the command line shortcut `~/path/to/IDE/webstorm.sh` or if you have added it to `/usr/local/bin/` when prompted in the setup wizard, do you still see the same error?
