### ISSUE TITLE
Run autocompletion script

### ISSUE THREAD

**Issue by captn3m0** [tfutils/tfenv#93]
On activating/deactivating a new version of terraform, the following 2 commands must be run:

```
terraform -install-autocomplete
terraform -uninstall-autocomplete
```

Since the completion scripts are version dependent, I cannot add this to my bashrc anymore.

**Comment by bizxta** [comment]
note, simply running either of those two commands simply adds the complete calls to bashrc/zshrc. It would require reloading bash/zsh before it is applied (or sourcing the rc files). Would need a better solution that just running that

**Comment by Zordrak** [comment]
I think that tfenv automatically issuing calls that will modify the user environment files is potentially dangerous. With the addition from the comment above that tfenv execution would not have the scope to reload the user's shell it seems limited in value.

I would suggest using a local bash function or alias to include the autocomplete call when issuing a tfenv install in a manner that suits your use case.
